# Generated by Django 2.1.2 on 2020-01-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('Instance', '0004_auto_20200120_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'heartbeat_instance',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, default=None, null=True)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'heartbeat_detail',
            },
        ),
        migrations.CreateModel(
            name='HeartbeatConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hb_tag', models.TextField(blank=True, default=None, null=True)),
                ('hb_yml_name', models.CharField(max_length=50)),
                ('schedule', models.IntegerField(default=120)),
                ('enabled', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo', verbose_name='customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_set', to='customer.User')),
            ],
            options={
                'db_table': 'heartbeat_config',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heartbeat_protocol',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heartbeat_status',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('heartbeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_heartbeat', to='heartbeat.HeartbeatConfig')),
            ],
            options={
                'db_table': 'heartbeat_url',
            },
        ),
        migrations.AddField(
            model_name='heartbeatconfig',
            name='hb_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartbeat.Protocol'),
        ),
        migrations.AddField(
            model_name='heartbeatconfig',
            name='instances',
            field=models.ManyToManyField(through='heartbeat.ConfigInstance', to='Instance.instance'),
        ),
        migrations.AddField(
            model_name='heartbeatconfig',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_set', to='customer.User'),
        ),
        migrations.AddField(
            model_name='detail',
            name='heartbeat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_heartbeat', to='heartbeat.HeartbeatConfig'),
        ),
        migrations.AddField(
            model_name='configinstance',
            name='heartbeat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartbeat.HeartbeatConfig'),
        ),
        migrations.AddField(
            model_name='configinstance',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instance.instance'),
        ),
        migrations.AddField(
            model_name='configinstance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartbeat.Status'),
        ),
    ]
