# Generated by Django 2.1.2 on 2020-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0003_remove_heartbeatconfig_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='configinstance',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
