# Generated by Django 2.1.2 on 2020-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0004_configinstance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeatconfig',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
