# Generated by Django 2.1.2 on 2020-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0005_heartbeatconfig_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeatconfig',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
