# Generated by Django 2.1.2 on 2020-05-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instance', '0004_auto_20200120_0747'),
        ('heartbeat', '0006_auto_20200225_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigInstance',
            new_name='HeartbeatInstance',
        ),
        migrations.AlterField(
            model_name='detail',
            name='heartbeat',
            field=models.ForeignKey(db_column='hid', on_delete=django.db.models.deletion.CASCADE, related_name='detail_heartbeat', to='heartbeat.HeartbeatConfig'),
        ),
        migrations.AlterField(
            model_name='heartbeatconfig',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='url',
            name='heartbeat',
            field=models.ForeignKey(db_column='hid', on_delete=django.db.models.deletion.CASCADE, related_name='url_heartbeat', to='heartbeat.HeartbeatConfig'),
        ),
    ]
