version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.12-alpine
        ports:           
            - 8080:8080
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/backend/api_server/django_static
    postgres:
        restart: always
        image: postgres
        ports:
            - 5432:5432
        environment:
            FILLA_DB_USER: letron
            FILLA_DB_PASSWORD: l@tr0n2019
            FILLA_DB_DATABASE: letron_operation
            POSTGRES_USER: postgres
            PGDATA: /data/postgres
        volumes:
            - ./docker/postgres/data:/data/postgres
           # - pgdata:/var/lib/postgresql/data
            - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    api:
        extends:
            file: docker-common.yml
            service: backend
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/api_server/django_static
        links:
            - postgres
        expose:
            - 8080

volumes:
    static_volume: {}

