# Generated by Django 2.1.2 on 2019-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='nid_id',
            new_name='nid',
        ),
        migrations.AlterField(
            model_name='instance',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
