# Generated by Django 2.1.2 on 2019-12-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instance', '0002_auto_20191204_0515'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instance',
            table='instance',
        ),
    ]
