# Generated by Django 2.1.2 on 2020-01-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instance', '0003_auto_20191204_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_isp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instance.isp'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instance.region'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instance.status'),
        ),
    ]
