# Generated by Django 2.1.2 on 2020-01-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instance', '0004_auto_20200120_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('max_url_num', models.IntegerField()),
                ('max_monitor_num', models.IntegerField()),
                ('min_interval_num', models.IntegerField()),
                ('instance', models.ManyToManyField(to='Instance.instance')),
            ],
            options={
                'db_table': 'customer_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('credential', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo')),
            ],
            options={
                'db_table': 'customer_user',
            },
        ),
    ]
