# Generated by Django 2.1.2 on 2020-01-31 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heartbeat', '0002_auto_20200131_0355'),
        ('Instance', '0004_auto_20200120_0747'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instance.instance')),
            ],
            options={
                'db_table': 'customer_instance',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relate_to_customer', to='customer.CustomerInfo')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='cid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
