# Generated by Django 2.1.2 on 2020-03-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instance', '0004_auto_20200120_0747'),
        ('customer', '0005_auto_20200131_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert40x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('total_bucket', models.IntegerField()),
                ('error_bucket', models.IntegerField()),
                ('alerting', models.BooleanField(default=False)),
                ('interval', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo')),
            ],
            options={
                'db_table': 'alert_40x',
            },
        ),
        migrations.CreateModel(
            name='Alert50x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('total_bucket', models.IntegerField()),
                ('error_bucket', models.IntegerField()),
                ('alerting', models.BooleanField(default=False)),
                ('interval', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo')),
            ],
            options={
                'db_table': 'alert_50x',
            },
        ),
        migrations.CreateModel(
            name='AlertNot20030x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerting_time', models.FloatField()),
                ('recovery_time', models.FloatField()),
                ('bucket', models.IntegerField()),
                ('history_avg', models.FloatField(default=0)),
                ('alerting', models.BooleanField(default=False)),
                ('interval', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo')),
            ],
            options={
                'db_table': 'alert_not_200_30x',
            },
        ),
        migrations.CreateModel(
            name='AlertNotifyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='LevelDownConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(blank=True, null=True)),
                ('down_percentage_alert', models.FloatField()),
                ('down_percentage_recovery', models.FloatField()),
                ('bucket', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo', verbose_name='customer')),
            ],
            options={
                'db_table': 'level_down_config',
            },
        ),
        migrations.CreateModel(
            name='LevelDownInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_down_monitors', to='alert.LevelDownConfig')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instance.instance')),
            ],
            options={
                'db_table': 'level_down_instance',
            },
        ),
        migrations.CreateModel(
            name='LevelRttConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(blank=True, null=True)),
                ('rtt_percentage_alert', models.FloatField()),
                ('rtt_percentage_recovery', models.FloatField()),
                ('rtt_threshold', models.FloatField()),
                ('bucket', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInfo', verbose_name='customer')),
            ],
            options={
                'db_table': 'level_rtt_config',
            },
        ),
        migrations.CreateModel(
            name='LevelRttInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_rtt_monitors', to='alert.LevelRttConfig')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instance.instance')),
            ],
            options={
                'db_table': 'level_rtt_instance',
            },
        ),
    ]
